Features/posts
developershash/DH-Portal-Backend pull request #1
Opened 2021-08-20 12:39 UTC by Roshan-Kumar-Sharma

I have added the **Joi** validation for **posts** by creating a **postSchema**. It must be included in the **posts.controller.js** to **validate the content of posts**

2021-08-20 12:55 UTC, shubdev07 requested changes
1. Tags should have a max of 5 items in array

2021-08-20 12:57 UTC, shubdev07 commented on api/v1/posts/posts.validation.js
> +const postSchema = Joi.object({
Rename it to "createPostValidate"

2021-08-20 13:21 UTC, Roshan-Kumar-Sharma commented on api/v1/posts/posts.validation.js
> +const postSchema = Joi.object({
changes done.

2021-08-21 12:34 UTC, shubdev07 approved these changes

2021-08-21 12:34 UTC, merged